# Generated by Django 3.1.2 on 2020-11-08 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tare_measurement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('active', models.BooleanField()),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelfstatus.container')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfstatus.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpotState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfstatus.productspot')),
                ('tag_present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfstatus.producttag')),
            ],
        ),
        migrations.AddField(
            model_name='productspot',
            name='last_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelfstatus.producttag'),
        ),
        migrations.AddField(
            model_name='productspot',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfstatus.shelf'),
        ),
        migrations.CreateModel(
            name='ProducContainerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_measurement', models.FloatField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfstatus.container')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfstatus.product')),
            ],
        ),
    ]
