# Generated by Django 3.1.2 on 2020-11-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelfstatus', '0002_auto_20201108_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspot',
            name='last_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelfstatus.producttag'),
        ),
    ]
