# Generated by Django 3.1.2 on 2020-11-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfstatus', '0003_auto_20201114_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspot',
            name='position',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='productspot',
            name='position_name',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
