# Generated by Django 3.1.2 on 2020-11-15 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shelfstatus', '0004_auto_20201114_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producttag',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
