# Generated by Django 3.1.2 on 2020-11-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfstatus', '0005_auto_20201115_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
