# Generated by Django 3.1.3 on 2020-11-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelfstatus', '0006_auto_20201115_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='container',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.AddField(
            model_name='producttag',
            name='relation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelfstatus.productcontainerrelation'),
        ),
    ]
