# Generated by Django 3.1.3 on 2020-12-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelfstatus', '0007_auto_20201126_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='tare_measurement',
            new_name='weight',
        ),
    ]
