# Generated by Django 3.1.3 on 2020-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfstatus', '0008_auto_20201205_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='tag',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
